todo/urls.py
from django.urls import path
from . import views
from todo.models import Task

app_name = "todo"

urlpatterns = [
	path('', views.TaskListView.as_view(), name = 'index'),
	path('saveTask', views.saveTask, name = 'saveTask'),
	path('delete/<int:id>', views.delete, name = 'delete'),
	path('edit/', views.editTask, name = 'editTask'),
]

todoList/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('todo/', include('todo.urls')),
    path('', RedirectView.as_view(url = '/todo/')),
]

todo/models.py
from django.db import models

class Task(models.Model):
	name = models.CharField(max_length = 255)
	options = (
		('d', 'done'),
		('nd', 'Not Done'),
		)
	status = models.CharField(max_length = 2, choices = options, default = 'nd')
	date_added = models.DateField(auto_now_add = True)

	def __str__(self):
		return self.name

todo/views.py
from django.shortcuts import render, redirect
from django.views.generic.list import ListView
from todo.models import Task

class TaskListView (ListView):
	model = Task
	context_object_name = 'tasks'
	template_name = 'todo/index.html'

	def get_queryset(self):
		queryset = Task.objects.order_by('date_added')[:10]
		return queryset

def saveTask(request):
	if request.method == 'POST':
		task = request.POST.get('task')
		task = Task(name = task)
		task.save()
		return redirect('todo:index')

def delete(request, id):
	task = Task.objects.get(id=id)
	task.delete()
	return redirect('todo:index')


def editTask(request):
	if request.method == 'POST':
		taskId = request.POST.get('id')
		task = request.POST.get('task')
		taskObj = Task.objects.get(id=taskId)
		taskObj.name = task
		taskObj.save()
		return redirect('todo:index')

todo/templates/todo/base.html
<!DOCTYPE html>
{%load static%}
<html lang = "en-US">
	<head>
		<link rel = "stylesheet" href = "{%static 'bootstrap.min.css'%}">
		<link rel = "stylesheet" href = "{%static 'custom.css'%}">
	</head>

	<body>
		<div class = "container">
			<div class = "row">
				<div class = "col-md-4">
					{%block form%}
					{%endblock%}
				</div>
				<div class = "offset-md-1 col-md-7">
					{%block info%}
					{%endblock%}
				</div>
			</div>
		</div>


		<script src = "{%static 'jquery-3.5.1.min.js'%}"></script>

		{%block otherJS%}
		{%endblock%}
	</body>
</html>

todo/templates/todo/index.html
{%extends "todo/base.html"%}

{%block form%}
<h3 class = "mt-3">Todo List</h3>
<hr>
<form method = "POST" action = "{%url 'todo:saveTask'%}">
	{%csrf_token%}
	<input class = "form-control" type = "text" placeholder = "Enter a Task" name = "task"><br>
	<input type = "hidden" value = ' ' name = "id">
	<input class = "btn btn-primary btn-block" value = "Add Task" type = "submit">
</form>

<div class = "bg-info p-4 text-light mt-5">
	<p>! In case you get stuck, double click on the input field, to add a new task</p>
</div>
{%endblock%}

{%block info%}
<div class = "mt-3">
	<h3>Let's Organise Your day</h3>
	<hr>
	{%for task in tasks%}
	<div>
		<button class = "btn btn-primary" id = "task{{task.id}}" onclick = "editTask('task{{task.id}}')">{{task.name}}</button>
		<a href = "{%url 'todo:delete' task.id%}" class = "btn btn-danger">Delete</a>
		<hr>
	</div>
	{%endfor%}
</div>
{%endblock%}

{%block otherJS%}
<script>
	function editTask(id){
		var elem = document.getElementById(id);
		var text = elem.innerHTML;
		$('input[name="task"]').val(text);
		$('input[type="submit"]').val('Update Task').removeClass('btn-primary').addClass('btn-info')
		$('input[name="id"]').val(id.replace('task', ''));
		$('form').attr('action', "{%url 'todo:editTask'%}");
	}

	$('input[name="task"]').dblclick(function(){
		$("input[type='submit']").val('Add Task').removeClass('btn-info').addClass('btn-primary')
		$("input[type='text']").val(' ');
	})
</script>
{%endblock%}